### PR TITLE
dotnet server - return user info on successful REST registration

### PR DESCRIPTION
**Pull request by ghost**
on a successful registration through the REST API:

A response containing details and an access token are returned to facilitate further use of the account.
This will be especially useful in the mobile app. It is also more secure than alternative approaches.
```
{
  "user": {
    "username": "SomeBody",
    "phoneNumber": "18004567890"
  },
  "apikey": "W2ThJ7xqtB3znyj7g0KF4jU2HJbcqdg1Un8eLXAV"
}
```

### CODE REVIEW

**Comment by ghost** [comment]
you may merge this

**Comment by ghost** [comment]
I'm writing a bunch of documentation with instructions for the API, so we can add that to the mobile app.

**Comment by ghost** [comment]
Docs are ready: https://github.com/0xFireball/BetaGo/blob/dotnet-server-dev/docs/devnotes/dotnet-server-api.md

**Comment by ghost** [comment]
See https://github.com/0xFireball/BetaGo/blob/dotnet-server-dev/docs/devnotes/dotnet-server-api.md#consuming-the-rest-api for info about api

**Comment by ghost** [comment]
next we need to integrate the mobile app to work with this API

**Comment by xeliot** [comment]
Test the app first on your device or something. And then create a separate branch to test the API and then if there are no problems then we will merge.

**Comment by ghost** [comment]
the app will need to be pretty much rewritten. I'll start some time soon

**Comment by xeliot** [comment]
the app won't need to be rewritten. All you need to do is change the server part to work with your API

**Pull request merged**
